function writeFieldData(filedir,filename)

filename = [filename '.vtk'];

fileID = fopen(fullfile(filedir, filename),'wt');
fprintf(fileID, [...
    '<# vtk DataFile Version 4.2',...
    'vtk output\n',...
    'ASCII\n',...
    'FIELD FieldData 2\n',...
    'lambda 1 1 double\n',...
    '2959999.75\n',...
    'METADATA\n',...
    'INFORMATION 0']);

end